//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_info
    {
        public int Info_id { get; set; }
        public int Product_id { get; set; }
        public string Creator_company { get; set; }
        public System.DateTime Release_date { get; set; }
        public string Annotation { get; set; }
    
        public virtual products products { get; set; }
    }
}
